a= input("my name is:")
b= input("my father name is:")
c= input("my mother name is:")
d= input("my brother name is:")
print("My name is :",a)
print("My father name is",b)
print("my mother name is:",c)
print("my brother name is:",d)